services:
  - type: web
    name: hitbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: TARGET_URL
        value: ""
      - key: REQUEST_COUNT
        value: "5"
      - key: TIMEOUT
        value: "10"
      - key: USE_DIRECT_CONNECTION
        value: "false"
      - key: MAX_PROXY_RETRIES
        value: "3"
      - key: SEARCH_DELAY
        value: "2"
      - key: REQUEST_DELAY
        value: "3"
      - key: RANDOMIZE_DELAYS
        value: "true"
      - key: SIMULATE_USER_BEHAVIOR
        value: "true" 